package com.tuenti.contest.domain.enu;

public enum ButtonActionEnum {
	
	SYMBOL_A, SYMBOL_B, SYMBOL_C, SYMBOL_D,	SYMBOL_E, SYMBOL_F,	SYMBOL_G, SYMBOL_H, SYMBOL_I,
	SYMBOL_J, SYMBOL_K,	SYMBOL_L, SYMBOL_M,	SYMBOL_N, SYMBOL_O,	SYMBOL_P, SYMBOL_Q,	SYMBOL_R,
	SYMBOL_S, SYMBOL_T,	SYMBOL_U, SYMBOL_V,	SYMBOL_W, SYMBOL_X, SYMBOL_Y, SYMBOL_Z,
	SYMBOL_a, SYMBOL_b, SYMBOL_c, SYMBOL_d,	SYMBOL_e, SYMBOL_f,	SYMBOL_g, SYMBOL_h, SYMBOL_i,
	SYMBOL_j, SYMBOL_k,	SYMBOL_l, SYMBOL_m,	SYMBOL_n, SYMBOL_o,	SYMBOL_p, SYMBOL_q,	SYMBOL_r,
	SYMBOL_s, SYMBOL_t,	SYMBOL_u, SYMBOL_v,	SYMBOL_w, SYMBOL_x, SYMBOL_y, SYMBOL_z,
	SYMBOL_0, SYMBOL_1, SYMBOL_2, SYMBOL_3,	SYMBOL_4, SYMBOL_5,	SYMBOL_6, SYMBOL_7,	SYMBOL_8, SYMBOL_9,
	CTRL_SPACE,
	CTRL_CHANGE_CASE
}
